"""Schema package exports for the BiasLens ML service API."""

from app.api.schemas.counterfactual_schema import (
    COUNTERFACTUAL_RESPONSE_EXAMPLE,
    CounterfactualCandidateResponse,
    CounterfactualEvaluationResponse,
    CounterfactualRequest,
    CounterfactualResponse,
    UPLOAD_COUNTERFACTUAL_RESPONSE_EXAMPLE,
    UploadCounterfactualResponse,
)
from app.api.schemas.error_schema import ErrorResponse
from app.api.schemas.explain_schema import (
    EXPLAIN_RESPONSE_EXAMPLE,
    ExplainRequest,
    ExplainResponse,
    ExplainerMethodResponse,
    FeatureContribution,
    LimeExplanationResponse,
    ProxyAttributionResponse,
    ProxySignalResponse,
    ShapExplanationResponse,
    TopProbabilityResponse,
)
from app.api.schemas.fairness_schema import (
    FAIRNESS_RESPONSE_EXAMPLE,
    FairnessResponse,
    GroupMetric,
)
from app.api.schemas.health_schema import HealthResponse, RootResponse
from app.api.schemas.metrics_schema import (
    METRICS_RESPONSE_EXAMPLE,
    ArtifactMetricsInfo,
    CacheMetricsInfo,
    MetricsResponse,
    ModelMetricsInfo,
    SavedMetricsInfo,
)
from app.api.schemas.prediction_schema import (
    PREDICTION_REQUEST_EXAMPLE,
    PREDICTION_RESPONSE_EXAMPLE,
    PredictionRequest,
    PredictionResponse,
)
from app.api.schemas.report_schema import (
    REPORT_RESPONSE_EXAMPLE,
    ROLE_COMPARISON_REQUEST_EXAMPLE,
    ROLE_COMPARISON_RESPONSE_EXAMPLE,
    TEXT_REPORT_REQUEST_EXAMPLE,
    TEXT_REPORT_RESPONSE_EXAMPLE,
    UPLOAD_REPORT_RESPONSE_EXAMPLE,
    UPLOAD_ROLE_COMPARISON_RESPONSE_EXAMPLE,
    ExtractedFeaturesResponse,
    ReportResponse,
    RoleComparisonItem,
    RoleComparisonRequest,
    RoleComparisonResponse,
    RoleFitExplanation,
    TextReportRequest,
    TextReportResponse,
    UploadReportResponse,
    UploadRoleComparisonResponse,
)
from app.api.schemas.resume_schema import ParseUploadResponse

__all__ = [
    "COUNTERFACTUAL_RESPONSE_EXAMPLE",
    "CounterfactualCandidateResponse",
    "CounterfactualEvaluationResponse",
    "CounterfactualRequest",
    "CounterfactualResponse",
    "UPLOAD_COUNTERFACTUAL_RESPONSE_EXAMPLE",
    "UploadCounterfactualResponse",
    "ErrorResponse",
    "EXPLAIN_RESPONSE_EXAMPLE",
    "ExplainRequest",
    "ExplainResponse",
    "ExplainerMethodResponse",
    "FAIRNESS_RESPONSE_EXAMPLE",
    "FairnessResponse",
    "FeatureContribution",
    "GroupMetric",
    "HealthResponse",
    "LimeExplanationResponse",
    "METRICS_RESPONSE_EXAMPLE",
    "MetricsResponse",
    "ArtifactMetricsInfo",
    "CacheMetricsInfo",
    "ModelMetricsInfo",
    "RootResponse",
    "ProxyAttributionResponse",
    "ProxySignalResponse",
    "PREDICTION_REQUEST_EXAMPLE",
    "PREDICTION_RESPONSE_EXAMPLE",
    "PredictionRequest",
    "PredictionResponse",
    "REPORT_RESPONSE_EXAMPLE",
    "ROLE_COMPARISON_REQUEST_EXAMPLE",
    "ROLE_COMPARISON_RESPONSE_EXAMPLE",
    "TEXT_REPORT_REQUEST_EXAMPLE",
    "TEXT_REPORT_RESPONSE_EXAMPLE",
    "UPLOAD_REPORT_RESPONSE_EXAMPLE",
    "UPLOAD_ROLE_COMPARISON_RESPONSE_EXAMPLE",
    "ExtractedFeaturesResponse",
    "ParseUploadResponse",
    "ReportResponse",
    "RoleComparisonItem",
    "RoleComparisonRequest",
    "RoleComparisonResponse",
    "RoleFitExplanation",
    "ShapExplanationResponse",
    "SavedMetricsInfo",
    "TextReportRequest",
    "TextReportResponse",
    "TopProbabilityResponse",
    "UploadReportResponse",
    "UploadRoleComparisonResponse",
]
