group: default
targets:
  backend:
    context: .
    dockerfile: infra/docker/Dockerfile.backend
    platforms:
      - linux/amd64
      - linux/arm64
  frontend:
    context: .
    dockerfile: infra/docker/Dockerfile.frontend
    platforms:
      - linux/amd64
      - linux/arm64
  ml-service:
    context: .
    dockerfile: infra/docker/Dockerfile.ml-service
    platforms:
      - linux/amd64
      - linux/arm64
