FROM nginx:1.27-alpine
COPY infra/nginx/nginx.conf /etc/nginx/nginx.conf
COPY infra/nginx/conf.d /etc/nginx/conf.d
COPY infra/nginx/performance.conf /etc/nginx/includes/performance.conf
COPY infra/nginx/gzip.conf /etc/nginx/includes/gzip.conf
COPY infra/nginx/cache-policies.conf /etc/nginx/includes/cache-policies.conf
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
